FROM ubuntu:18.04

RUN apt-get update \
  && apt-get install -y unzip \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

RUN apt-get update && apt-get install -y vim

COPY . /home

RUN pip install -r ./requirements.txt

EXPOSE 8080

# ENTRYPOINT ["python3"]